UniversityApp/Models/DepartmentHira.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;

namespace UniversityApp.Models
{
    public class DepartmentHira
    {
        public int Id { get; set; }
        [Required (ErrorMessage = "Provide Department Code")]
        [StringLength(7,MinimumLength = 2, ErrorMessage = "code must be two (2) to seven (7) characters long")]
       
        public string Code { get; set; }
        [Required(ErrorMessage = "Please enter a department Name")]
        public string Name { get; set; }

    }
}

UniversityApp/Controllers/DepartmentHiraController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityApp.Manager;
using UniversityApp.Models;

namespace UniversityApp.Controllers
{
    public class DepartmentHiraController : Controller
    {
        DepartmentHiraManager _aDepartmentHiraManager=new DepartmentHiraManager();

        
        
        public ActionResult SaveDepartment()
        {

            return View();
        }
        [HttpPost]
        public ActionResult SaveDepartment(DepartmentHira department)
        {
            if (ModelState != null)
            {
                ViewBag.department = _aDepartmentHiraManager.SaveDepartment(department);
                return View();
            }
            //ViewBag.department = aDepartmentManager.SaveDepartment(department);
            return View();
        }
	}
}

UniversityApp/Views/DepartmentHira/SaveDepartment.cshtml
@model UniversityApp.Models.DepartmentHira
@{
    ViewBag.Title = "SaveDepartment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SaveDepartment</h2>


    @section style{
    <style>
        .field-validation-error {
            color: red;
            font-style: italic;
        }
    </style>
    }


        @using (Html.BeginForm("SaveDepartment", "DepartmentHira", FormMethod.Post))
        {

            <fieldset>

                <legend>Save Department</legend>

                <table>
                    <tr>
                        <td>@Html.LabelFor(m => m.Code)</td>
                        <td>@Html.TextBoxFor(m => m.Code)</td>
                        <td>@Html.ValidationMessageFor(m => m.Code)</td>
                    </tr>
                    <tr>
                        <td>@Html.LabelFor(m => m.Name)</td>
                        <td>@Html.TextBoxFor(m => m.Name)</td>
                        <td>@Html.ValidationMessageFor(m => m.Name)</td>
                    </tr>
                    <tr>
                        <td></td>

                        <td>
                            <input type="submit" value="Save">

                        </td>
                    </tr>

                </table>

                @if (ViewBag.department != null)
                {
                     <label> @ViewBag.department</label>
                    
                }
               

                
                

            </fieldset>

        }
@section scripts{

        <script src="~/Scripts/jquery-1.10.2.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}
    
    

UniversityApp/Views/DepartmentHira/SaveDepartment1.cshtml
@model UniversityApp.Models.DepartmentHira
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Save Department</title>

    
    <style>
        
         .field-validation-error {
             color: red;
             font-style: italic;
         }
    </style>
   
</head>
<body>
<div>
    
        @using (Html.BeginForm("SaveDepartment", "DepartmentHira", FormMethod.Post))
{

    <fieldset>

        <legend>Save Department</legend>

        <table>
            <tr>
                <td>@Html.LabelFor(m => m.Code)</td>
                <td>@Html.TextBoxFor(m => m.Code)</td>
                <td>@Html.ValidationMessageFor(m => m.Code)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(m => m.Name)</td>
                <td>@Html.TextBoxFor(m => m.Name)</td>
                <td>@Html.ValidationMessageFor(m => m.Name)</td>
            </tr>
            <tr>
                <td></td>

                <td>
                    <input type="submit" value="Save">

                </td>
            </tr>

        </table>

        
            <label> @ViewBag.department</label>
        

    </fieldset>
    
}
   
</div>
<script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>